---
title: "maps"
author: "Thalie Emond"
date: "17/02/2022"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages(c("dplyr", "ggplot2", "tidyverse", "psych", "haven", "maptools", "doBy", "gganimate", "gpclib", "readxl", "gapminder", "transformr", "gifski", "viridisLite", "viridis", "plotly", "plyr", "kableExtra", "readr", "scales", "tweenr", "countrycode", "sf", "giscoR", "magick", "foreign"))

library(dplyr)
library(ggplot2)
library(tidyverse)
library(psych)
library(haven)
library(maptools)
library(doBy)
library(gganimate)
library(gpclib)
gpclibPermit()
library(readxl)
library(transformr)
library(gifski)
#remotes::install_github("mccormackandrew/mapcan")
#library(mapcan)
library(viridisLite)
library(viridis)
library(plotly)
#library(plyr)
library(kableExtra)
library(readr)
library(scales)
library(tweenr)
library(countrycode)
library(sf)
library(giscoR)
library(magick)
library(foreign)
library(likert)
```

```{r data cleaning}


load("HC_df.RData")

HC_MAP.df <- HC.df %>%
  select(Year, Country, country_code, incident_type,bias_mot) %>%
  group_by(Year, incident_type, country_code, bias_mot) %>%
  count(Country) %>%
  rename(num_incidents = n)

## Population - Eurostats

demo <- read.csv("demo_migration.csv")
demo <- demo %>% 
  select(TIME_PERIOD, geo, OBS_VALUE) %>%
  rename(Year = TIME_PERIOD, demo = OBS_VALUE)
  
popu <- read.csv("entirepopu.csv")
popu <- popu %>% 
  select(TIME_PERIOD, geo, OBS_VALUE) %>%
  rename(Year = TIME_PERIOD, popu = OBS_VALUE)

fbpopu <- read.csv("foreignbornpopu.csv")
fbpopu <- fbpopu %>% 
  select(TIME_PERIOD, geo, OBS_VALUE) %>%
  rename(Year = TIME_PERIOD, fbpopu = OBS_VALUE)

### merging
iso2EURMAP <- gisco_countrycode %>%
  select(iso2c, CNTR_CODE)




EUR_pop.df <- left_join(x = demo, y = popu, by = c("geo", "Year"))
EUR_pop.df <- left_join(x = EUR_pop.df, y = fbpopu, by = c("geo", "Year"))
EUR_pop.df <- left_join(x = EUR_pop.df, y = iso2EURMAP, by = c("geo" = "iso2c"))
#### merge with bigger data set

hc_map2 <- left_join(x = EUR_pop.df, y = HC_MAP.df,
                     by = c("CNTR_CODE"="country_code", 
                            "Year"))

## Percentage of attacks out of immigrant population 

hc_map2 <- hc_map2 %>%
  mutate(immigrant_prop = (fbpopu / popu)* 100, popu_thsnds = popu / 100000) 

hc_map2 <- hc_map2 %>%
  filter(!is.na(Country))

hc_map2 <- hc_map2 %>%
  mutate(HC_ratio = num_incidents / popu_thsnds)

###### Cleaning NAs from initial dataset
hc_map3 <- hc_map2 %>%
  filter(!is.na(HC_ratio))

## load map from eurostate geodata (2021)
cntries <- gisco_get_countries(year = 2020,
                               resolution = 20) %>%
           st_transform(3035) 

cntries$NAME_ENGL[cntries$NAME_ENGL == "Russian Federation"] <- "Russia"
cntries$NAME_ENGL[cntries$NAME_ENGL == "Czechia"] <- "Czech Republic"
cntries$NAME_ENGL[cntries$NAME_ENGL == "United States"] <- "United States of America"


hc_map5 <- cntries %>%
  left_join(hc_map3, by = c("NAME_ENGL" = "Country"))

hc_map5 <- hc_map5 %>%
  filter(NAME_ENGL != "United States of America" & NAME_ENGL != "Canada" &
           NAME_ENGL != "Kazakhstan" & NAME_ENGL != "Kyrgyzstan" & 
           NAME_ENGL != "Tajikistan" & NAME_ENGL != "Turkmenistan" & 
           NAME_ENGL != "Uzbekistan")


### UK
UKmap <- gisco_get_nuts(year = "2021",
               nuts_level = "2",
               country = "United Kingdom",
               resolution = 20)
uk_HC <- read_xlsx("uk_hatecrime.xlsx", sheet = "Table 1", range = "B7:L51")

uk_HC <- uk_HC %>%
  rename(area = `Police Force Area`) %>%
  filter(area != "Englandd")

uk_HC$`2019/20 b,c` <- as.numeric(uk_HC$`2019/20 b,c`)

sapply(uk_HC[,3:10], as.numeric)

uk_HC <- uk_HC %>%
  select(!`2011/12` & 
           !`2012/13` & 
           !`2013/14` & 
           !`2014/15` & 
           !`2020/21`) %>%
  rename(`2020` = `2019/20 b,c`,
         `2019` = `2018/19`,
         `2018` = `2017/18`,
         `2017` = `2016/17`,
         `2016` = `2015/16`)

uk_HC2 <- pivot_longer(data = uk_HC, cols = 2:6, names_to = "Year")
uk_HC2$Year <- as.numeric(uk_HC2$Year)


#### Popu
ukpopu2016 <- read_xls("ukpopu2016.xls", sheet = "1.1", range = "B9:H13")
ukpopu2017 <- read_xls("ukpopu2017.xls", sheet = "1.1", range = "B9:H13")
ukpopu2018 <- read_xls("ukpopu2018.xls", sheet = "1.1", range = "B9:H13")
ukpopu2019 <- read_xls("ukpopu2019.xls", sheet = "1.1", range = "B9:H12")
ukpopu2020 <- read_xls("ukpopu2020.xls", sheet = "1.1", range = "B4:H6")

ukpopu <- data.frame(
  popu = c(ukpopu2016[4,2], ukpopu2017[4,2], ukpopu2018[4,2], ukpopu2019[3,2], ukpopu2020[2,3]))

ukfbpopu <- data.frame(
  fbpopu = c(ukpopu2016[4,7], ukpopu2017[4,7], ukpopu2018[4,7], ukpopu2019[3,7], ukpopu2020[2,7]))

colnames(ukpopu) <- c(2016, 2017, 2018, 2019, 2020)
colnames(ukfbpopu) <- c(2016, 2017, 2018, 2019, 2020)

  
ukpopu <- pivot_longer(data = ukpopu, cols = 1:5, names_to = "Year", names_repair = "minimal")

ukfbpopu <- pivot_longer(data = ukfbpopu, cols = 1:5, names_to = "Year", names_repair = "minimal")

ukpopu <- left_join(ukpopu, ukfbpopu, by = "Year")

ukpopu <- ukpopu %>%
  rename(popu = value.x, fbpopu = value.y)

ukpopu[5,2] <- ukpopu[5,2] / 1000
ukpopu[5,3] <- ukpopu[5,3] / 1000

ukpopu$Year <- as.numeric(ukpopu$Year)


UK_cc <- data.frame(CNTR_CODE = c("UK", "UK", "UK", "UK", "UK"))

uk_HC_clean <- cbind(UK_cc, uk_HC2)

uk_HC_clean <- uk_HC_clean %>%
  left_join(ukpopu, by = "Year")

ukgeom <- data.frame(geometry = c(hc_map5[4024,18], hc_map5[4024,18],hc_map5[4024,18],hc_map5[4024,18],hc_map5[4024,18]))

ukgeom <- pivot_longer(ukgeom, cols = 1:5, names_to = "geometry", names_repair = "minimal")

uk_HC_clean <- cbind(uk_HC_clean, ukgeom[,2])


### percentage and stuff 

uk_HC_clean <- uk_HC_clean %>%
  mutate(immigrant_prop = (fbpopu / popu)* 100, HC_ratio = num_incidents / popu) 

hc_map6 <- hc_map5 %>%
  full_join(uk_HC_clean, by = c("CNTR_ID" = "CNTR_CODE", "Year", "num_incidents", "popu", "fbpopu", "geometry" = "value", "HC_ratio", "immigrant_prop"))


###

#save(hc_map6, file = "hc_map6.RData")

load("hc_map6.RData")
```

```{r new}



HCRatio_map <- hc_map6 %>%
  ggplot() +
  # Layers
  geom_sf(data = cntries, fill = "grey80", color = "gray53") +
  geom_sf(data = filter(hc_map6, Year == 2016),
          aes(fill = HC_ratio), color = "gray53") +
  geom_sf(data = filter(hc_map6, Year == 2017),
          aes(fill = HC_ratio), color = "gray53") +
  geom_sf(data = filter(hc_map6, Year == 2018),
          aes(fill = HC_ratio), color = "gray53") +
  geom_sf(data = filter(hc_map6, Year == 2019),
          aes(fill = HC_ratio), color = "gray53") +
  geom_sf(data = filter(hc_map6, Year == 2020),
          aes(fill = HC_ratio), color = "gray53") +
  # Labs
  coord_sf(xlim = c(2200000, 7150000), ylim = c(1380000, 5500000), expand = F) +
  labs(subtitle = "NUTS0 regions (2020)",
       caption = "Eurostat, © EuroGeographics for the administrative boundaries",
       fill = "Index") +
  scale_fill_viridis_c(option = "mako",
                       na.value = "grey80",
                       direction = -1) +
  # Theme
  theme(plot.caption = element_text(size = 15, face = "italic"),
        legend.position = "bottom",
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
    plot.background = element_rect(fill = "#f3f6f4", color = NA),
    panel.background = element_rect(fill = "#f3f6f4", color = NA),
    legend.background = element_rect(fill = "#f3f6f4", color = NA)
        ) +
  # Animation
  
  transition_layers(layer_length = 5, 
                    transition_length = 2,
                    layer_names = c(" ", "2016", "2017", "2018", "2019", "2020"),
                    from_blank = F, keep_layers = c(Inf, 0, 0, 0,0, 0)) +
  enter_fade() + exit_fade() +
  labs(title = "Number of Reported Xenophobic Incidents in \n Proportion to Total Population Across Europe in {closest_layer}")

animate(HCRatio_map, fps = 10, duration = 20,
        width = 600, height = 500, renderer = gifski_renderer())



```

```{r GESIS}
#devtools::install_github("expersso/gesis")

EVS <- read.spss("ZA7503_v2-0-0.sav", to.data.frame=TRUE)

EVS$S020 <- as.numeric(levels(EVS$S020))[EVS$S020]

EVS1 <- EVS %>%
  filter(S020 > 2015) %>%
  summarise(S003, S009, pwght, S020, X025, G006, G007_35_B, G007_36_B, G033, G036, G038, G040, G041, G043, G052, G257)

#EVS1[,1:16] <- sapply(EVS1[,1:16],as.numeric)
#sapply(EVS1[,1:16], class)

EVS1 <- EVS1 %>%
  rename(iso3 = S003, 
         iso3_2 = S009, 
         pwght = pwght, 
         Year = S020, 
         educ_level = X025, 
         national_pride = G006, 
         trust_oth_religion = G007_35_B, 
         trust_oth_nationality = G007_36_B, 
         imptce_birthplace = G033, 
         imptce_speaklang = G036, 
         imt_takeaway_jobs = G038, 
         imt_incr_probs = G040, 
         imt_welfare = G041, 
         imt_customs = G043, 
         imt_impactdev = G052, 
         close_country = G257)

#save(EVS1, file = "EVS1.RData")

load("EVS1.RData")

```


```{r  recoding formulas}

imt_views <- select(EVS1, 
                    imt_takeaway_jobs,imt_incr_probs, imt_customs, imt_welfare)


recoding_4answers <- function(X){
  Y <- ifelse(is.na(X), NA,
              ifelse(X == 1, "Very close",
                     ifelse(X == 2, "Close",
                            ifelse(X == 3, "Not very close",
                                   ifelse(X == 4, "Not close at all", NA)))))
  Y <- factor(Y, levels = c("Very close", "Close", "Not very close", "Not close at all"))
  return(Y)
}


EVS1_imt_likert <- imt_views %>%
  likert()

Qs_imt_views <- names(imt_views)

## MISSING LEVEL

likert_chart1 <- plot(EVS1_imt_likert,
     group.order=names(imt_views),
     plot.percents = F,
     plot.percent.low = FALSE,
     plot.percent.high = FALSE,
     centered = T,
     wrap=20,
     legend.position = "right",
     center = 3.5) +
  scale_fill_viridis(discrete=TRUE) +
  theme(panel.grid = element_line(color = NA),
        plot.title = element_text("Views on Immigrants"),
        axis.text.y = element_text(colour = "black"))

likert_chart1


```

```{r Hungary & Romania data}
RO_HU_att <- EVS1 %>%
  filter(iso3_2 == "RO" & iso3_2 == "HU") 
  

```
